### ISSUE TITLE
Question: How should NPC Grunts be used?

### ISSUE THREAD

**Issue by lavahot** [Gerdofal/roll20-CyberpunkRED_Gerdofal_BETA#24]
I'm a bit confused as to how NPC grunts should be used. Like, do they get their own token?

**Comment by Gerdofal** [comment]
Actually, no. The NPC grunt sheet view is intended to be a very quick way to roll for a lot of grunt NPCs without needing to attach to a token. If a NPC is important enough to have an attached sheet, I would use the character view for them.
